FXP-2289 Add links to graphs
mozilla/perfcompare pull request #193
Opened 2022-07-14 10:43 UTC by esanuandra

2022-07-15 13:07 UTC, beatrice-acasandrei approved these changes

2022-07-15 20:28 UTC, kimberlythegeek requested changes
Looks good--however I think that we should have some hover action where this icon changes color so that it behaves more like a typical link.

Perhaps use `color: inherit` on hover? or we could do the reverse, using the theme defaults for on hover.

2022-07-15 20:31 UTC, kimberlythegeek commented on src/components/CompareResults/CompareResultsTableRow.tsx
> +        >
can you also add alt text or an aria label for accessibility?

2022-07-20 15:02 UTC, kimberlythegeek approved these changes

2022-07-21 06:43 UTC, merged