recent revisions only fetch on render #244
mozilla/perfcompare pull request #284
Opened 2022-12-06 17:50 UTC by NikolaDojic

closes #244

2022-12-07 10:01 UTC, esanuandra commented
Hey @NikolaDojic! Thank you for your contribution. When you finish this add the `ready for review` label.

2022-12-07 11:32 UTC, NikolaDojic commented
Hey, not a problem :)

![Screenshot_20221207_123141](https://user-images.githubusercontent.com/24179802/206168751-c69ee1da-c60a-4d39-b415-83b316d15bac.png)

@esanuandra, I don't think that I can, unless I'm missing something.  I think writing permission is needed for that.

2022-12-11 13:02 UTC, NikolaDojic commented
ready for review

2022-12-12 08:44 UTC, esanuandra requested changes
Looks good. Could you please look into the failing for codecov/project? Maybe a rebase would help.

2022-12-12 08:44 UTC, esanuandra commented on src/__tests__/utils/test-utils.tsx
> +  return function SroreProvider({ children }: ChildrenProps) {
typo?

2022-12-12 08:44 UTC, esanuandra commented on src/__tests__/hooks/useHandleChangeSearch.test.ts
> +  it('shold update inputHelperText to contain an error if search text does not match email or hash', () => {
typo

2022-12-12 10:11 UTC, NikolaDojic commented on src/__tests__/utils/test-utils.tsx
> +  return function SroreProvider({ children }: ChildrenProps) {
thanks, and sorry about that

2022-12-12 10:24 UTC, NikolaDojic commented
> Looks good. Could you please look into the failing for codecov/project? Maybe a rebase would help.

@esanuandra the codecov report kind of baffles me. 
![Screenshot_20221212_112133](https://user-images.githubusercontent.com/24179802/207021875-a3e594a6-3230-4cec-a601-672ff2128db0.png)

it states that all lines are covered in the affected files, but still fails. can we trigger a re-run?

2022-12-13 12:21 UTC, esanuandra approved these changes
nice work

2023-01-05 06:14 UTC, kimberlythegeek approved these changes

2023-01-05 06:14 UTC, merged