Drag and drop revision rows #170
mozilla/perfcompare pull request #286
Opened 2022-12-07 21:26 UTC by NikolaDojic

closes #170

2022-12-09 12:46 UTC, NikolaDojic commented
I don't have the right permission to add labels to the PRs, but you can consider this ready for review.

2022-12-12 12:38 UTC, kimberlythegeek requested changes
Thanks! I would ask that you add some sort of UI "affordance" to indicate to users that these items are draggable.

This is a resource on drag-and-drop affordances: https://www.nngroup.com/articles/drag-drop/

at the very least I would expect an icon that suggests the items can be dragged. I appreciate your contribution :smile:

2022-12-13 08:28 UTC, beatrice-acasandrei commented
@NikolaDojic Thanks for your contributions! Could you update the PR so that it's no longer out-of-date (rebase with upstream/staging)?

2022-12-13 12:17 UTC, NikolaDojic commented
thanks for the reviews :) 
@beatrice-acasandrei rebased,
@kimberlythegeek that is a good point, thanks, I've added a draggable icon indicator at the beginning of the draggable rows.

2022-12-13 15:16 UTC, beatrice-acasandrei commented
While dragging the cursor's icon changes which might be confusing since it indicates you can't drop the item.

2022-12-13 15:45 UTC, NikolaDojic commented
> While dragging the cursor's icon changes which might be confusing since it indicates you can't drop the item.

@beatrice-acasandrei 
hmm, I'm not sure that I follow. 
What is happening currently is that we have one cursor icon that is visible on hover, which is an open-hand icon that indicates that the element is draggable.
After the drag start event,  the cursor changes to a closed hand, which is the default browser behavior and it indicates that the item is being dragged (this is due to the `draggable="true"` attribute ). 
The cursor changes to an open hand after the element is dropped inside the table (since it is hovering over the row).

Can you help me understand which part is problematic? 
thanks :)

2022-12-14 11:05 UTC, NikolaDojic commented
@beatrice-acasandrei thanks for the update.
hmm, interesting. It could be os related since I'm working on Arch Linux

2022-12-14 12:53 UTC, beatrice-acasandrei commented on src/utils/helpers.ts
> +  console.warn(
I assume `console.warn` was used for testing purposes and can be removed.

2023-01-05 06:39 UTC, kimberlythegeek commented
Hi--unsure if I'm missing something, but I've just run this locally and the drag-and-drop does not seem to be working

2023-01-05 06:39 UTC, kimberlythegeek requested changes
Hi--unsure if I'm missing something, but I've just run this locally and the drag-and-drop does not seem to be working

2023-01-05 10:36 UTC, NikolaDojic commented
> Hi--unsure if I'm missing something, but I've just run this locally and the drag-and-drop does not seem to be working

that is weird :/ 
Can you tell me more about your env? 
and maybe git log output?

here is a screen recording from my local branch, which is, according to git same as my remote branch.
The last commit has hash `c4657e583c994714760ea7c1ad571cb137005c98`
https://user-images.githubusercontent.com/24179802/210759257-f247be9c-cf3e-4f97-a689-7f5e9630b30e.mp4

2023-01-09 11:17 UTC, kimberlythegeek commented
Hi--unsure what was causing the error before, but it appears to be working now!

2023-01-09 11:17 UTC, kimberlythegeek approved these changes

2023-01-12 12:42 UTC, esanuandra commented
Hey @NikolaDojic, can you update de pr again please so we can merge this?

2023-01-12 12:47 UTC, NikolaDojic commented
@esanuandra  updated

2023-01-12 15:20 UTC, merged