fix: memoize SearhResultList component
mozilla/perfcompare pull request #310
Opened 2023-03-07 18:38 UTC by betty-alagwu

This pull request fixes #140 .

It prevents the unnecessary rerender of the `SearchResultsList` component by wrapping it in a `React.memo`.

2023-03-13 10:43 UTC, betty-alagwu commented
Hey @Carla-Moz @kimberlythegeek Please review and share your feedback when you get a chance. Thanks.

2023-03-22 11:41 UTC, kimberlythegeek commented
I apologize--I thought I already left a comment on this!!

Thank you for contribution! :smile: It appears that your patch does not resolve the issue. I am using react devtools with the option "Highlight updates when components render" option enabled.

2023-03-22 11:41 UTC, kimberlythegeek requested changes
I apologize--I thought I already left a comment on this!!

Thank you for contribution! smile It appears that your patch does not resolve the issue. I am using react devtools with the option "Highlight updates when components render" option enabled.

2023-03-29 17:22 UTC, kimberlythegeek commented
thanks for your contribution. I haven't seen any activity recently, and the contribution period for Outreachy is almost over, so I'm closing this PR. feel free to re-open if you would like to continue working on this.

2023-03-29 17:22 UTC, closed without merging