PCF-378 Fix aria-label attributes Part 1
mozilla/perfcompare pull request #607
Opened 2024-02-23 16:20 UTC by esanuandra

This PR addresses [Fix aria-label attributes](https://mozilla-hub.atlassian.net/browse/PCF-378)

- [x] Add aria-label on Link components
- [x] Add/modify aria-label for some button components

2024-02-27 13:07 UTC, esanuandra commented on src/components/CompareResults/RevisionRow.tsx
>                </IconButton>
I think we need to remove one `aria-label` either from the `IconButton` or from the `Link`.

2024-02-27 13:08 UTC, esanuandra commented on src/components/CompareResults/RevisionRow.tsx
>                </IconButton>
I think we need to remove one `aria-label` either from the `IconButton` or from the `Link`.

2024-02-27 17:42 UTC, julienw requested changes
Thanks for looking at this Andra!

I left a bunch of comments, tell me what you think!

In (not very) short:
* there are places where we don't need aria-label at all (I recommend that you look at the elements using the devtools' awesome accessibility panel that makes it possible to inspect all the accessibility properties in the page)
* there are places where a tooltip might be more appropriate, when the information can be useful for a sighted user. To keep simple for now, we can use the HTML `title` attribute that will give a tooltip automatically when the user hovers on the element for more than a few seconds. Please double check with the accessibility panel that this is properly exposed to assistive technologies.

Also I believe that we can improve how the `title` or `aria-label` are redacted. I think they can be shorter.

For example there are links where the aria-label  is "link to bla bla", but because it is a link, the assistive technology will already say to the user that it is a link! Rather just write as if there was text. For example "Remove revision" is good. For a link this coulod be "Go to XXX" instead of "Link to XXX".

I think we can use both aria-label or tooltip sometimes, as they don't have the same purpose always. A tooltip could give some more information where the aria-label would just be the blunt description. But as a first pass, let's keep it simple and use just one or the other, so that we don't risk saying different things.

Also it would be good that all text we add as tooltip or aria-label go to the Strings file.

2024-02-27 17:42 UTC, julienw commented on src/components/Search/SaveCancelButtons.tsx
> +        aria-label='cancel edit'
These ones don't need any aria-label, as they already have a good text. 

[Rule 1 of ARIA: don't use ARIA](https://www.deque.com/blog/top-5-rules-of-aria/)

2024-02-27 17:42 UTC, julienw commented on src/components/CompareResults/RevisionHeader.tsx
> +          aria-label={`link to revision jobs in treeherder for ${shortHash}`}
A tooltip could be useful here (instead of the aria-label) for also sighted users.

2024-02-27 17:42 UTC, julienw commented on src/components/App.tsx
>                </Link>
We don't need aria-label here, the text is already good.
(cf Rule 1 of ARIA)

2024-02-27 17:42 UTC, julienw commented on src/components/Search/SelectedRevisionItem.tsx
> +                  aria-label={`link to revision jobs in treeherder for ${revisionHash}`}
As said above for a similar situation, we probably can use a title here, as this can be useful to sighted users.

2024-03-01 11:00 UTC, julienw approved these changes
Thanks, this looks better!

I made a few wording suggestions, tell me what you think! (also I'm not a super good english speaker so feel free to adjust or ask somebody who knows better)

If you apply them you can land the patch without another review.

But if you do want a last review, please add the new changes to a separate commit so that I can look at that one only :-)

2024-03-01 12:35 UTC, esanuandra commented on src/components/CompareResults/RevisionRow.tsx
> +              title={Strings.components.expandableRow.title}
right

2024-03-01 13:49 UTC, merged