#766 Modified confidence filter to display results by high confidence by default
mozilla/perfcompare pull request #777
Opened 2024-10-09 18:08 UTC by bhekidaweti

Updated filters to sort by confidence level to high by default

2024-10-09 18:43 UTC, hibaa03 commented
HI, for the CI tests failing read [this](https://github.com/mozilla/perfcompare?tab=readme-ov-file#running-all-validators-and-tests) part of the README.

2024-10-09 18:56 UTC, bhekidaweti commented
Thanks, I am working on it.

2024-10-11 13:57 UTC, julienw commented on src/components/CompareResults/ResultsTable.tsx
> +  }, []);
can you please explain why you used this effect in addition to the default state above?
Thanks

2024-10-11 13:58 UTC, julienw commented on src/components/CompareResults/ResultsTable.tsx
> +    new Map([['confidence', new Set(['High'])]]), // ColumnID -> Set<Values to remove>// Default confidence filter
Have you tried the code locally? This does the opposite of what you think: this _removes_ all items with the "high" confidence, we want to do the opposite.

2024-10-11 13:59 UTC, julienw requested changes
thanks for your contribution,
please note that the code does the opposite of what's needed: it removes all results with the "high" confidence instead of keeping them only.

Thanks!

2024-11-07 13:57 UTC, closed without merging