Persist Column Filters in URL (#765)
mozilla/perfcompare pull request #783
Opened 2024-10-10 16:34 UTC by ST-KO

### **Overview**: This pull request implements functionality to persist column filters in the URL. Users can now refresh the page and maintain their selected filters, improving the overall user experience. This addresses issue #765.

### **Changes Made**:

1. **Filters Persist in the URL**

Implemented the useEffect hook that reads the filter parameters from the URL when the component mounts, ensuring that the selected filters are applied even after a page refresh.

https://github.com/user-attachments/assets/3cf763ad-90f0-4ac4-8eb6-f62208f88f91

2. **Shared Filtered View URL**

Update the URL with the applied filters in the existing _onToggleFilter_ method, allowing users to share the URL and they will see the same filtered results.

https://github.com/user-attachments/assets/1be944b7-acf5-4f67-a52d-433d1473e2d0

3. **URL Updates as Filters are Applied or Removed**

This functionality is implemented in the existing  _onToggleFilter_ and _onClearFilter_ methods, where parameters are dynamically added or deleted. I utilised the existing **_useRawSearchParams_** custom hook to prevent unnecessary page re-rendering. This ensures that the URL dynamically updates as filters are added or removed.

https://github.com/user-attachments/assets/4ad43c32-7981-4dde-be01-d11327b4076e

2024-10-16 01:48 UTC, ST-KO commented
Hi, I just wanted to mention that the tests were passing in the first pull request. After refactoring the code, the tests started failing, even though all tests passed locally in VS Code. I’ll investigate further. Thanks.

2024-10-16 06:24 UTC, Carla-Moz commented
Hi! I'll help you investigate this tomorrow!  Thanks for your patience.

2024-10-16 20:42 UTC, Carla-Moz requested changes
Please see my comments!

2024-10-17 14:04 UTC, ST-KO commented
> @ST-KO Hi there! Thanks for your detailed PR. Before I jump into your code, I highly recommend creating unique descriptions for your commit messages. They are all the same so I have very little idea what to expect in the commits. Could you please go ahead and create a fresh PR with amended commit messages? That would help a lot.

Hi @Carla-Moz, 

Thank you for your feedback, and I apologise for not providing clear and unique commit messages earlier. I have now created a fresh pull request [](https://github.com/mozilla/perfcompare/pull/788) for your review. Looking forward to your feedback.

2024-10-17 15:13 UTC, closed without merging

2024-10-17 15:13 UTC, Carla-Moz commented
Closing due to updated PR https://github.com/mozilla/perfcompare/pull/788