adding standard deviation column
mozilla/perfcompare pull request #785
Opened 2024-10-11 16:09 UTC by Joice-crypto

## **PR Description**

This PR is related to issue #771.

### **What was done:**
- Added a column for standard deviation as requested, for both "base" and "new" data.

### **Screenshots:**
![stdev](https://github.com/user-attachments/assets/e49d746d-2cfe-4aa8-b668-a4b810a28c84)

### **Tests:**
- The new functionality was rigorously tested using Snapshot Tests to ensure consistent output and integrity.
- Additionally, the JavaScript code has been validated with `npm run lint` to maintain code quality and adherence to style guidelines.

### **Checklist:**
- [x] The code follows the project's guidelines.
- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my solution works or that my feature functions correctly.
- [x] All new and existing tests passed.

---

### **Steps to Test:**
1. Check the new standard deviation column in the data.

2024-10-15 03:13 UTC, Carla-Moz requested changes

2024-10-15 03:13 UTC, Carla-Moz commented on src/components/CompareResults/ResultsTable.tsx
> +  },
Good job! 

However, could you please set the standdevbase and standdevnew column header to `text-align: center` so it looks better?

2024-10-15 03:25 UTC, Carla-Moz commented on src/components/CompareResults/RevisionRow.tsx
> +        </div>
You also forgot to calculate and add the comparison sign.

2024-10-17 03:50 UTC, Joice-crypto commented
Hello @Carla-Moz, could you please check the changes?

2024-10-21 14:50 UTC, Carla-Moz approved these changes
Good job!

2025-01-28 00:09 UTC, closed without merging